class Ranking(list):
    '''
    A list of document IDs generated by an interleaving method
    '''
    def __hash__(self):
        return hash(tuple(self))

class TeamRanking(Ranking):
    '''
    A list of document IDs generated by an interleaving method,
    including teams
    '''
    def __init__(self, team_indices):
        '''
        Initialize self.teams

        team_indices: indices for self.teams
        '''
        self.teams = {i: set() for i in team_indices}

    def __hash__(self):
        '''
        TeamRanking can be a key by which
        rankings with the same document ID list
        and the same team assignment are the same
        '''
        return hash((tuple(self),
            frozenset([(k, frozenset(v)) for k, v in self.teams.items()])))
